"""Added prime column

Revision ID: 53a7c7d3fffd
Revises: 7d9320a989f2
Create Date: 2024-04-21 19:25:02.096248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a7c7d3fffd'
down_revision: Union[str, None] = '7d9320a989f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prime_status', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'prime_status')
    # ### end Alembic commands ###
