"""Added likes table

Revision ID: 6962fe96b9d6
Revises: 53a7c7d3fffd
Create Date: 2024-04-23 09:59:25.267533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6962fe96b9d6'
down_revision: Union[str, None] = '53a7c7d3fffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
