"""Added likes table

Revision ID: b9f0d30d8879
Revises: 6ea135acfe94
Create Date: 2024-04-23 10:37:22.272998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f0d30d8879'
down_revision: Union[str, None] = '6ea135acfe94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'receiver_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'receiver_id',
               existing_type=sa.Integer(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###
